[package]
name = "kramqpus"
version = "0.1.0"
authors = ["John Eckersberg <jeckersb@redhat.com>"]
edition = "2018"
description = "AMQP 1.0 Interconnect"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
